config/routes.rb
MajorLeaguePong::Application.routes.draw do
  match 'signup/:invitation_token' => "users#new", :as => :signup_with_invite
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login
  match 'user/edit' => 'users#edit', :as => :edit_current_user

  resources :invitations
  resources :visuals
  resources :sessions
  resources :users
  resources :players, except: :new
  resources :teams
  resources :rounds  

  resources :games do
    resources :rounds
    resources :shots
  end

  root :to => "players#index"
end

app/models/round.rb
class Round < ActiveRecord::Base
  belongs_to :game, :counter_cache => true
  has_many :shots, :dependent => :destroy
  accepts_nested_attributes_for :shots, :allow_destroy => true
  validates_presence_of :number
  validates_numericality_of :number

  after_create :punch_asshole
  after_destroy :forgive_asshole

  def punch_asshole
    asshole(true)
  end

  def forgive_asshole
    asshole(false)
  end

  private

  def asshole(increment)
    shots_away = Shot.where("cup != 0 and cup < 11 and cup is not null and round_id = ? and team_id = ?", self.id, self.game.away.id)
    shots_home = Shot.where("cup != 0 and cup < 11 and cup is not null and round_id = ? and team_id = ?", self.id, self.game.home.id)

    [shots_away, shots_home].each do |shots|
      if shots.count == 2
        shots.each do |shot|
          if shot.cup == 0
            if increment 
              shot.player.increment!(:assholes)
              shot.team.increment!(:assholes)
            else
              shot.player.decrement!(:assholes)
              shot.team.decrement!(:assholes)
            end
            break
          end
        end
      end
    end
  end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  load_and_authorize_resource
  helper_method :sort_column, :sort_direction  
  
  def index
    @game = Game.find(params[:game_id])
    @rounds = @game.rounds.order("number asc")

    flash.now[:info] = "This game has not yet been scored." if @rounds.blank?
  end

  def show
    @round = Round.find(params[:id])
  end

  def new
    @game = Game.find(params[:game_id])
    #@round = @game.rounds.build
    #@round.number = @game.rounds.count > 1 ? @game.rounds.count + 1 : 1
  end

  def edit
    @game = Game.find(params[:game_id])
    @round = Round.find(params[:id])
  end

  def create
    @game = Game.find(params[:game_id])
    @round = @game.rounds.new(params[:round])

    if @round.save
      redirect_to(game_rounds_path(@game), :flash => { :success => 'Round was successfully created.' })
    else
      render :action => "new"
    end
  end

  def update
    @game = Game.find(params[:game_id])
    @round = Round.find(params[:id])

    if @round.update_attributes(params[:round])
      redirect_to(game_rounds_path(@game), :flash => { :success => 'Round was successfully updated.' })
    else
      render :action => "edit" 
    end
  end

  def destroy
    @game = Game.find(params[:game_id])
    @round = Round.find(params[:id])
    # LightHouse bug #4386 => dependent => destroy called before before_destroy effectively destroy all the shots
    # before analysis of whoever the asshole is can be done
    @round.forgive_asshole 
    @round.destroy

    redirect_to(game_rounds_url(@game))
  end

  private

  def sort_column
    params[:sort] ||= "number"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end



end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/views/rounds/_form.html.erb
<% if @round.errors.any? %>
  <div class="error">
    <% @round.errors.full_messages.each do |msg| %>
      <%= msg %><br/>
    <% end %>
  </div>
<% end %>

<%= form_for @game do |f| %>
  <table class="sortable">
    <thead>
      <tr>
        <th>Number</th>
        <th><%= @game.away_players[0].name %></th>
        <th><%= @game.away_players[1].name %></th>
        <th><%= @game.away_players[2].name %></th>
        <th><%= @game.home_players[0].name %></th>
        <th><%= @game.home_players[1].name %></th>
        <th><%= @game.home_players[2].name %></th>
        <th>Remove</th>
      </tr>
    </thead>
    <tbody>
      <%= f.fields_for :rounds do |round_form| %>
        <%= render 'round_fields', :f => round_form %>
      <% end -%>
    </tbody>
  </table>

  <p>
    <%= link_to_add_fields "Add Round", f, :rounds %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/rounds/_round_fields.html.erb
<% 6.times { f.object.shots.build } if f.object.new_record? -%>
<tr>
  <td>
    <%= f.text_field :number, :size => 3 %>
  </td>

  <% i = 0 -%>
  <%= f.fields_for :shots do |shot_form| %>
    <%= render :partial => 'shot_fields', :locals => { :f => shot_form, :i => i } %>
    <% i += 1 -%>
  <% end -%>

  <td>
    <%= f.check_box(:_destroy) %>
    <%= f.hidden_field :id %>
  </td>
</tr>

app/views/rounds/_shot_fields.html.erb
<td>
  <%= f.select :cup, [["Miss", 0], 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, ["No Shot", ""]] %>
  <%= f.hidden_field :id %>
  <%= f.hidden_field :game_id, :value => @game.id %>
  <%= f.hidden_field :player_id, :value => @game.players[i].id %>
  <%= f.hidden_field :team_id, :value => i < 3 ? @game.away.id : @game.home.id %>
</td>

app/views/rounds/edit.html.erb
<h2>Editing round</h2>
<p>
  <%= link_to "Delete Round", game_round_path(@game, @round), :method => :delete, :confirm => "Are you sure?" %> | <%= link_to "Back", game_rounds_path(@game) %>
</p>

<%= render 'form' %>

app/views/rounds/index.html.erb
<h2>
  <%= "#{@game.away.name} at #{@game.home.name}" %>
</h2>
<h4>
  <%= @game.time.to_s(:long) %>
</h4>

<% unless @game.rounds.blank? -%>
<table>
  <thead>
    <tr>
      <th>Round</th>
      <th><%= @game.away_players[0].name %></th>
      <th><%= @game.away_players[1].name %></th>
      <th><%= @game.away_players[2].name %></th>
      <th><%= @game.home_players[0].name %></th>
      <th><%= @game.home_players[1].name %></th>
      <th><%= @game.home_players[2].name %></th>
    </tr>
  </thead>
  <tbody>
    <% @rounds.each do |round| -%>
      <tr>
        <td><%= link_to round.number, edit_game_round_path(@game, round) %></td>
        <% round.shots.each do |shot| -%>
          <td><%= render_shot(shot) %></td>
        <% end -%>
      </tr>
    <% end -%>
  </tbody>
</table>
<% end -%>

<% if can? :manage, Round -%>
  <p><%= link_to "New Round", new_game_round_path %></p>
<% end -%>

app/views/rounds/new.html.erb
<h2>
  <%= "#{@game.away.name} at #{@game.home.name}" %>
</h2>
<h4>
  <%= @game.time.to_s(:long) %>
</h4>

<%= render 'form' %>

app/views/rounds/show.html.erb
<div class="grid_16">
<p id="notice"><%= notice %></p>

<p>
  <b>Game:</b>
  <%= @round.game_id %>
</p>

<p>
  <b>Number:</b>
  <%= @round.number %>
</p>

</div>