config/routes.rb
MajorLeaguePong::Application.routes.draw do
  match 'signup/:invitation_token' => "users#new", :as => :signup_with_invite
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login
  match 'user/edit' => 'users#edit', :as => :edit_current_user

  resources :invitations
  resources :visuals
  resources :sessions
  resources :users
  resources :players, except: :new
  resources :teams
  resources :rounds  

  resources :games do
    resources :rounds
    resources :shots
  end

  root :to => "players#index"
end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :sender, :class_name => 'User'
  has_one :recipient, :class_name => 'User'
  belongs_to :team

  validates_presence_of :recipient_email
  validate :recipient_is_not_registered
  validate :team_is_not_full, :unless => "team.blank?"

  before_create :generate_token

  private

  def team_is_not_full
    errors.add :team_id, 'is already full.' if team.players.count >= 3
  end

  def recipient_is_not_registered
    errors.add :recipient_email, 'is already registered.' if User.find_by_email(recipient_email)
  end

  def generate_token
    self.token = Digest::SHA1.hexdigest([Time.now, rand].join)
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  load_and_authorize_resource
  def new
    @invitation = Invitation.new
  end

  def create
    @invitation = Invitation.new(params[:invitation])
    @invitation.sender = current_user
    if @invitation.save
      UserMailer.invitation(@invitation, signup_with_invite_url(@invitation.token)).deliver
      flash[:success] = "Thank you, invitation sent."
      redirect_to players_path
    else
      render :action => 'new'
    end
  end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/_form.html.erb
<%= form_for(@invitation) do |f| %>
  <% if @invitation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invitation.errors.count, "error") %> prohibited this invitation from being sent:</h2>

      <ul>
      <% @invitation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :sender_id %><br />
    <%= f.text_field :sender_id %>
  </p>
  <p>
    <%= f.label :recipient_email %><br />
    <%= f.text_field :recipient_email %>
  </p>
  <p>
    <%= f.label :token %><br />
    <%= f.text_field :token %>
  </p>
  <p>
    <%= f.label :sent_at %><br />
    <%= f.datetime_select :sent_at %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/invitations/edit.html.erb
<h1>Editing Invitation</h1>


<%= link_to 'Show', @invitation %> |
<%= link_to 'Back', invitations_path %>

app/views/invitations/index.html.erb
<h1>Listing invitations</h1>

<table>
  <tr>
    <th>Sender</th>
    <th>Recipient email</th>
    <th>Token</th>
    <th>Sent at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @invitations.each do |invitation| %>
  <tr>
    <td><%= invitation.sender_id %></td>
    <td><%= invitation.recipient_email %></td>
    <td><%= invitation.token %></td>
    <td><%= invitation.sent_at %></td>
    <td><%= link_to 'Show', invitation %></td>
    <td><%= link_to 'Edit', edit_invitation_path(invitation) %></td>
    <td><%= link_to 'Destroy', invitation, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Invitation', new_invitation_path %>

app/views/invitations/new.html.erb
<% if @invitation.errors.any? %>
  <div class="error">
    <% @invitation.errors.full_messages.each do |msg| %>
      <%= msg %><br/>
    <% end %>
  </div>
<% end %>

<%= form_for @invitation do |f| %>
  <%= field_set_tag "Invite" do %>
    <p>
      <%= f.label :name, "Friend's name" %><br />
      <%= f.text_field :name, :class => 'title' %>
    </p>
    <p>
      <%= f.label :recipient_email, "Friend's email address" %><br />
      <%= f.text_field :recipient_email, :class => 'text' %>
    </p>
    <p>
      <%= f.label :team_id, "Team" %><br />
      <%= f.select :team_id, Team.all.collect { |t| [t.name, t.id] }, { :include_blank => "Free Agent" } %>
    </p>
    <p><%= f.submit "Invite" %></p>
  <% end -%>
<% end -%>

app/views/invitations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sender:</b>
  <%= @invitation.sender_id %>
</p>

<p>
  <b>Recipient email:</b>
  <%= @invitation.recipient_email %>
</p>

<p>
  <b>Token:</b>
  <%= @invitation.token %>
</p>

<p>
  <b>Sent at:</b>
  <%= @invitation.sent_at %>
</p>


<%= link_to 'Edit', edit_invitation_path(@invitation) %> |
<%= link_to 'Back', invitations_path %>