config/routes.rb
MajorLeaguePong::Application.routes.draw do
  match 'signup/:invitation_token' => "users#new", :as => :signup_with_invite
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login
  match 'user/edit' => 'users#edit', :as => :edit_current_user

  resources :invitations
  resources :visuals
  resources :sessions
  resources :users
  resources :players, except: :new
  resources :teams
  resources :rounds  

  resources :games do
    resources :rounds
    resources :shots
  end

  root :to => "players#index"
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :shots, :dependent => :destroy
  has_many :rounds, :order => 'number', :dependent => :destroy
  accepts_nested_attributes_for :shots
  belongs_to :away, :class_name => 'Team'
  belongs_to :home, :class_name => 'Team'

  has_and_belongs_to_many :home_players, :class_name => 'Player', :association_foreign_key => "home_player_id"
  has_and_belongs_to_many :away_players, :class_name => 'Player', :association_foreign_key => "away_player_id"
  
  accepts_nested_attributes_for :rounds, :allow_destroy => true

  def to_param
    "#{id}-#{away.name}-#{home.name.gsub(/ /,"-")}"
  end

  def players
    away_players + home_players 
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  load_and_authorize_resource
  helper_method :sort_column, :sort_direction  

  def index
    @games = Game.includes(:away, :home, :rounds).order("#{sort_column} #{sort_direction}")
  end

  def show
    @game = Game.find(params[:id])
    flash.now[:info] = "This game has not yet been scored." if @game.rounds.blank?
  end

  def new
    @game = Game.new
  end
    
  def edit
    @game = Game.find(params[:id])
  end

  def create
    @game = Game.new(params[:game])

    if @game.save
      redirect_to(games_path, :flash => { :success => 'Game was successfully created.' })
    else
      render :action => "new" 
    end
  end

  def update
    @game = Game.find(params[:id])

    if @game.update_attributes(params[:game])
      redirect_to(@game, :flash => { :success => 'Game was successfully updated.' })
    else
      render :action => "edit"
    end
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy

      redirect_to(games_url)
  end

  private

  def sort_column
    params[:sort] ||= "time"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end

end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<% if @game.errors.any? %>
  <div class="error">
    <h4><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

    <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(@game) do |f| %>
  <%= field_set_tag 'Details' do %>
    <p>
      <%= f.label :time %><br />
      <%= f.datetime_select :time %>
    </p>

    <p>
      <%= f.label :away_id, "Away Team" %><br />
      <%= f.select :away_id, Team.all.collect { |t| [ t.name, t.id ] } %>
    </p>

    <p>
      <%= f.label :away_player_ids, "Away Players" %><br />
      <%= f.select :away_player_ids, Player.all.collect { |p| [ p.name, p.id ] }, { :selected => @game.away_player_ids }, { :multiple => true } %>
    </p> 

    <p>
      <%= f.label :home_id, "Home Team" %><br />
      <%= f.select :home_id, Team.all.collect { |t| [ t.name, t.id ] } %>
    </p> 

    <p>
      <%= f.label :home_player_ids, "Home Players" %><br />
      <%= f.select :home_player_ids, Player.all.collect { |p| [ p.name, p.id ] }, { :selected => @game.home_player_ids }, { :multiple => true } %>
    </p> 

    <p>
      <%= f.submit %>
    </p>
  <% end %>
<% end %>

app/views/games/edit.html.erb
<h2>Editing game</h2>

<%= render 'form' %>

app/views/games/index.html.erb
<div class="grid_16">
  <h3>Schedule</h1>
   <div class="grid_4 alpha">
    <h6><%= sortable "time" %></h6>
  </div>
  <div class="grid_4">
    <h6>Away</h6>
  </div>
  <div class="grid_4">
    <h6>Home</h6>
  </div>
  <div class="grid_4 omega">
    <h6>Rounds</h6>
  </div>
  <div class="clear"></div>

  <% @games.each do |game| %>
    <div class="grid_4 alpha">
      <p><%= link_to game.time.to_s(:short), game_rounds_path(game) %></p>
    </div>
    <div class="grid_4">
      <p>
          <%= game.away.name %>
      </p>
    </div>
    <div class="grid_4">
      <p>
          <%= game.home.name %>
      </p>
    </div>
    <div class="grid_4 omega">
      <p><%= game.rounds.count %></p>
    </div>
    <div class="clear"></div>
  <% end %>
 <% if can? :manage, Game %>
    <p>
      <%= link_to "Schedule a New Game", new_game_path %>
    </p>
  <% end %>


</div>

app/views/games/new.html.erb
<h2>New game</h2>

<%= render 'form' %>

app/views/games/show.html.erb
<h2>
  <%= "#{@game.away.name} at #{@game.home.name}" %>
</h2>
<h4>
  <%= @game.time.to_s(:long) %>
</h4>

<% unless @game.rounds.blank? -%>
<table>
  <thead>
    <tr>
      <th>Round</th>
      <th><%= @game.away_players[0].name %></th>
      <th><%= @game.away_players[1].name %></th>
      <th><%= @game.away_players[2].name %></th>
      <th><%= @game.home_players[0].name %></th>
      <th><%= @game.home_players[1].name %></th>
      <th><%= @game.home_players[2].name %></th>
    </tr>
  </thead>
  <tbody>
    <% @game.rounds.each do |round| -%>
      <tr>
        <td><%= round.number %></td>
        <% round.shots.each do |shot| -%>
          <td><%= render_shot(shot) %></td>
        <% end -%>
      </tr>
    <% end -%>
  </tbody>
</table>
<% end -%>

<% if can? :manage, Round -%>
  <p><%= link_to "Score Game", new_game_round_path(@game) %></p>
<% end -%>