config/routes.rb
MajorLeaguePong::Application.routes.draw do
  match 'signup/:invitation_token' => "users#new", :as => :signup_with_invite
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login
  match 'user/edit' => 'users#edit', :as => :edit_current_user

  resources :invitations
  resources :visuals
  resources :sessions
  resources :users
  resources :players, except: :new
  resources :teams
  resources :rounds  

  resources :games do
    resources :rounds
    resources :shots
  end

  root :to => "players#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>MajorLeaguePong</title>
    <%= stylesheet_link_tag 'screen', :media => "screen, projection" %>
    <%= stylesheet_link_tag 'print', :media => "print" %>
    <!--[if lt IE 8]>
    <%= stylesheet_link_tag 'ie', :media => "screen, projection" %>
    <![endif]-->
    <%= stylesheet_link_tag 'https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.10/themes/black-tie/jquery-ui.css', 'application' %>
    <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js" %>
    <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.10/jquery-ui.min.js" %>
    <%= javascript_include_tag 'highcharts-2.1.3.min', 'rails', 'application' %>
    <%= csrf_meta_tag %>
    <%= favicon_link_tag %>
  </head>
  <body>
    <div class="container">

      <div class="span-24" id="header">
        <div class="span-8">
          <%= link_to((image_tag "major_league_pong.png", :alt => "Major League Pong", :width => 300), root_path) %>
        </div>
        <div class="span-8 push-8 last">
          <% if logged_in? -%>
            <div class="box">
              <p class="loud bottom"><%= link_to current_user.username, current_user %> hit <%= pluralize(current_user.player.hit_count, 'cup') %> for <%= pluralize current_user.player.points, 'point' %> in the last <%= pluralize current_user.player.shots.count, 'shot' %> for an overall score of <%= number_with_precision current_user.player.opp %> and a hit percentage of <%= number_to_percentage current_user.player.hit_percentage * 100 %> with <%= pluralize current_user.player.suicides, 'suicide' %> and <%= pluralize current_user.player.assholes, 'asshole' %>.</p>
            </div>
          <% end -%>
        </div>
      </div>

      <div class="span-24" id="navigation">
        <div class="span-12">
          <h1><%= link_to "major league pong", root_path %></h1>
        </div>
        <div class="span-12 last">
          <ul>
            <% if logged_in? -%>
              <li class="large"><%= link_to_unless_current "Players", players_path %></li>
              <li class="large"><%= link_to_unless_current "Teams", teams_path %></li>
              <li class="large"><%= link_to_unless_current "Games", games_path %></li>
              <li class="large"><%= link_to_unless_current "Logout", logout_path %></li>
            <% else -%>
              <li class="large"><%= link_to_unless_current "Login", login_path %></li>
            <% end -%>
          </ul>
        </div>
      </div>

      <hr />

      <% unless flash.blank? -%>
        <div class="span-24">
          <% flash.each do |key, msg| %>
            <%= content_tag :div, msg, :class => key %>
          <% end %>
        </div>
      <% end -%>

      <div class="span-24" id="content">
        <%= yield %>
      </div>

      <div class="span-24" id="footer">
        <div class="span-8 quiet">
          <ul class="no-disc">
            <li>Fucking ideate</li>
            <li>Don't be greedy</li>
            <li>Don't be trendy</li>
            <li>Fucking start over</li>
            <li>Less is fucking more</li>
            <li>Read the fucking copy</li>
            <li>Use fucking alignment</li>
            <li>There is no fucking box</li>
            <li>Think fucking laterally</li>
            <li>Write a fucking design brief</li>
            <li>Use more fucking white space</li>
            <li>Pay attention to fucking detail</li>
            <li>Learn from your fucking mistakes</li>
            <li>Capitalize on the fucking experience</li>
          </ul>
        </div>
        <div class="span-8">
          <h2>Have a clear fucking hierarchy</h2>
        </div>
        <div class="span-8 last quiet">
          <ul class="no-disc">
            <li>Give a damn</li> 
            <li>Love your job</li>
            <li>Fucking simplify</li>
            <li>Fucking experiment</li>
            <li>Sans-fucking-serif</li>
            <li>Fucking do it again</li>
            <li>Educate your client</li>
            <li>Take a fucking chance</li>
            <li>Be a good fucking person</li>
            <li>Consider your fucking user</li>
            <li>Get over your fucking self</li>
            <li>Learn from your fucking peers</li>
            <li>Do it right the first fucking time</li>
            <li>Work outside of your fucking habits</li>
          </ul>
        </div>
      </div>
    </div>
  </body>
</html>